"""add index

Revision ID: b933f90b94bd
Revises: f0c251925652
Create Date: 2025-04-09 03:56:38.565114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b933f90b94bd'
down_revision: Union[str, None] = 'f0c251925652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_public_requests_created_at'), 'requests', ['created_at'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_requests_created_at'), table_name='requests', schema='public')
    # ### end Alembic commands ###
